Add NOAA D-RAP map to propagation plugin ?drapmap
miaowware/qrm2 pull request #457
Opened 2023-01-10 01:48 UTC by westjgames

### Description

Added a command to display the current NOAA D-RAP map (https://www.swpc.noaa.gov/products/d-region-absorption-predictions-d-rap)

Fixes 
N/A

### Type of change

- New feature 

### How has this been tested?

Bot was created on Discord, and added to a dev server. Commands were run:
?drapmap
?drap
?solarweather (this is failing in both current master and this branch)
flake8 run

### Checklist

- [ ] Issue exists for PR
- [x] Code reviewed by the author
- [x] Code documented (comments or other documentation)
- [x] Changes tested
- [x] All tests pass (see [`DEVELOPING.md`][0], if it exists)
- [x] [`CHANGELOG.md`][1] updated if needed
- [x] Informative commit messages
- [x] Descriptive PR title

[0]: /DEVELOPING.md
[1]: /CHANGELOG.md

2023-01-13 05:42 UTC, classabbyamp requested changes

2023-01-13 05:42 UTC, classabbyamp commented on CHANGELOG.md
> +- `?drapmap` command to display NOAA D Region Absorption Predictions map
```suggestion
- `?drapmap` command to display NOAA D Region Absorption Predictions map.

```

2023-01-13 05:42 UTC, classabbyamp commented on exts/propagation.py
> +    noaa_drap = "https://services.swpc.noaa.gov/images/animations/d-rap/global/d-rap/latest.png"
```suggestion
    noaa_drap_url = "https://services.swpc.noaa.gov/images/animations/d-rap/global/d-rap/latest.png"
```

2023-01-13 05:42 UTC, classabbyamp commented on exts/propagation.py
> +        embed.set_image(url=self.noaa_drap)
```suggestion
        embed.set_image(url=self.noaa_drap_url)
```

2023-01-13 05:42 UTC, classabbyamp commented on exts/propagation.py
> +        embed.title = "Current D-RAP Map"
this embed should also have a link to the source. see muf/fof2 for an example

2023-01-13 10:51 UTC, 0x5c requested changes
Also squash the commits together

2023-01-13 10:51 UTC, 0x5c commented on exts/propagation.py
> +    @commands.command(name="drapmap", aliases=["drap", "radioblackout", "blackout", "ionosphere"],
```suggestion
    @commands.command(name="drapmap", aliases=["drap", "radioblackout", "blackout"],
```
That alias is too vague. I'm on the fence about `radioblackout` and `blackout`, not sure if they should be removed or not.
If they go, the continuation on the next line should be moved back to this one.

2023-01-13 10:51 UTC, 0x5c commented on exts/propagation.py
> +        embed.title = "Current D-RAP Map"
```suggestion
        embed.title = "D Region Absorption Predictions (D-RAP) Map"
```

2023-01-15 05:30 UTC, westjgames commented
Whew. I need to learn git a bit better. Got there in the end. I think these changes are as requested.

2023-01-15 10:47 UTC, westjgames commented
Fixed the flake8 long line issue

2023-01-16 09:35 UTC, classabbyamp commented
can you edit the commit message (`git commit --amend`) to remove the extra lines from squashing and force-push?

2023-01-16 09:38 UTC, classabbyamp commented on exts/propagation.py
> +        "(https://www.swpc.noaa.gov/products/d-region-absorption-predictions-d-rap)\nData sources listed on the page."
```suggestion
        embed.description = \
            "Image from [swpc.noaa.gov](https://www.swpc.noaa.gov/products/d-region-absorption-predictions-d-rap)"
```

2023-01-17 11:33 UTC, 0x5c submitted a review, later dismissed

2023-01-17 11:35 UTC, 0x5c commented on exts/propagation.py
> +        "(https://www.swpc.noaa.gov/products/d-region-absorption-predictions-d-rap)\nData sources listed on the page."
lmao that's a line too longb

2023-01-17 17:16 UTC, classabbyamp requested changes

2023-01-17 17:16 UTC, classabbyamp commented on exts/propagation.py
> +            "Image from [swpc.noaa.gov](https://www.swpc.noaa.gov/products/d-region-absorption-predictions-d-rap)\nData sources listed on the page."
i don't think the "data sources listed" part is needed

2023-01-30 10:15 UTC, classabbyamp submitted a review, later dismissed

2023-01-30 10:24 UTC, classabbyamp approved these changes

2023-01-30 10:25 UTC, merged