update pycord
miaowware/qrm2 pull request #483
Opened 2024-05-17 16:20 UTC by classabbyamp

### Description

- requirements.txt: update py-cord to release version
- run.sh: respect $VIRTUAL_ENV

### Type of change

- Refactor/code cleanup 

### How has this been tested?

ran the bot

### Checklist

- [ ] Issue exists for PR
- [x] Code reviewed by the author
- [x] Code documented (comments or other documentation)
- [x] Changes tested
- [x] All tests pass (see [`DEVELOPING.md`][0], if it exists)
- [x] [`CHANGELOG.md`][1] updated if needed
- [x] Informative commit messages
- [x] Descriptive PR title

[0]: /DEVELOPING.md
[1]: /CHANGELOG.md

2024-08-11 05:39 UTC, 0x5c requested changes

2024-08-11 05:39 UTC, 0x5c commented on run.sh
> +    VIRTUAL_ENV="$BOTENV"
This should probably be the inverse definition, since there could be something else down the line that (mistakenly?) uses the venv standard var.

2024-08-11 05:39 UTC, 0x5c commented on main.py
> +from discord import utils as dutils
what's this? why the `dutils`?
I'm generally not a fan of changing valid python just for pyright...

2024-08-11 05:39 UTC, 0x5c commented on info.py
> +qrm is a <:miaowware_irl:678275824436379678> MiaowWare project."""
Does this line still work with prepended whitespace to make it align with the first one? Might be somewhat more readable with the empty line replaced by `\n` too?

2026-02-10 03:28 UTC, classabbyamp commented
example deprecation notice:

<img width="440" height="121" alt="image" src="https://github.com/user-attachments/assets/cf5ed0d9-204b-49f7-981f-0ad7ada03c75" />

2026-02-10 06:03 UTC, 0x5c approved these changes

2026-02-10 06:03 UTC, merged